### ISSUE TITLE
SDS011 nicht auslesbar

### ISSUE THREAD

**Issue by MNieddu91** [jp112sdl/HB-UNI-Sen-DUST#1]
Hallo Jérôme, 

gab es in irgendeine Änderung an den SDS011 Sensoren? Ich bekommen von Anbeginn nach dem Anlernen eine Sevicemeldung in RaspberryMatic "Sensor nicht verfügbar".
Den Sensor habe ich mit folgendem https://github.com/galch/DustViewerSharp schon auf Funktion getestet und dieser liefert korrekte Werte. 

Wenn ich im Serial Monitor schaue entdecke ich folgendes: 
```
08:15:38.603 -> AskSin++ v5.0.3 (Mar 27 2024 19:20:37)
08:15:38.642 -> Init SDS011
08:15:39.625 -> FW: -1.-1.-1
08:15:41.709 -> Address Space: 32 - 100
08:15:41.709 -> Radio init1
08:15:41.709 -> CC Version: 14
08:15:41.709 ->  - ready
08:15:41.709 -> Enable PinPolling: 8 - 1
08:15:41.752 -> *Sendeintervall: 60
08:15:41.752 -> *Messintervall : 10
08:15:41.752 -> *ReadRetryCount: 3
08:15:41.752 -> MEASURE... #1
08:15:42.264 -> FAIL - retry #1
08:15:43.973 -> FAIL - retry #2
08:15:45.738 -> FAIL - retry #3
08:15:47.449 -> FAIL - giving up
```

Er kann also scheinbar den Sensor nicht auslesen. Ein Verkabelungsfehler halte ich bei dem simplen Aufbau der Platine für ausgeschlossen. 

Hast du eine Idee ? 

Auf dem der Sensorplatine ist SDS011. 2.18.3 abgedruckt.

**Comment by jp112sdl** [comment]
Hi, das kann ich dir leider beantworten. 
Ich habe mich nicht weiter mit dem Projekt beschäftigt.
Der Sensor lief bei mir damals etwa 2 Jahre, dann hat der Lüfter nur noch Lärm gemacht und ich habe das Gerät ersatzlos entfernt.
Da bei dir schon das Init nicht klappt, müsste wohl die zuerst in der Library geschaut werden https://github.com/lewapek/sds-dust-sensors-arduino-library

**Comment by MNieddu91** [comment]
> Hi, das kann ich dir leider beantworten. Ich habe mich nicht weiter mit dem Projekt beschäftigt. Der Sensor lief bei mir damals etwa 2 Jahre, dann hat der Lüfter nur noch Lärm gemacht und ich habe das Gerät ersatzlos entfernt. Da bei dir schon das Init nicht klappt, müsste wohl die zuerst in der Library geschaut werden https://github.com/lewapek/sds-dust-sensors-arduino-library

Ich habe es gelöst. Ich trottel habe Pin A45 nicht auf dem PCB verlötet. Jetzt funktioniert der Sensor. 

Issue kann also geclosed werden. Aber gut ein Statusupdate in 2024 geben zu können, dass noch alles funktioniert.

**Comment by jp112sdl** [comment]
Ja, so is natürlich noch besser :)
